In [3]:
from solution_template import *
%load_ext autoreload
%autoreload 2

In [4]:
entity = Solution(glue_qqp_dir='data/QQP/', 
                  glove_vectors_path='data/glove.6B.50d.txt')

In [ ]:
#entity.create_glove_emb_from_file(file_path='data/glove.6B.50d.txt', inner_keys=entity.all_tokens, random_seed=entity.random_seed, rand_uni_bound=entity.emb_rand_uni_bound)

In [4]:
entity.glue_train_df['text_left']

0         How is the life of a math student? Could you d...
1                       How do I control my horny emotions?
2              What causes stool color to change to yellow?
3                               What can one do after MBBS?
4         Where can I find a power outlet for my laptop ...
                                ...                        
320755    Why might a girl feel bad when she gets a love...
320756    Have the Ancient Mayans been scientifically te...
320757    What is the best solution to the Kashmir confl...
320758    Are there any free public company financial da...
320759    What are the top books that teach Android eCom...
Name: text_left, Length: 320760, dtype: object

In [8]:
len(entity.dev_pairs_for_ndcg)

31095

In [9]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [32]:
def hadle_punctuation(inp_str: str) -> str:
    trans_table = str.maketrans({i:' ' for i in string.punctuation})
    out_str = inp_str.translate(trans_table)
    return out_str

In [33]:
print(entity.glue_train_df.iloc[0,2])
print(hadle_punctuation(entity.glue_train_df.iloc[0,2]))

How is the life of a math student? Could you describe your own experiences?
How is the life of a math student  Could you describe your own experiences 


In [34]:
def simple_preproc(inp_str: str) -> List[str]:
    out_str = inp_str.lower()
    out_str = hadle_punctuation(out_str)
    out_str = nltk.tokenize.word_tokenize(out_str)
    return out_str

In [35]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/karpov/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [56]:
pd.concat([entity.glue_train_df[['id_left']], entity.glue_train_df[['id_right']]], axis=0)

446540

In [64]:
entity.glue_train_df[['id_right']].rename(columns={'id_right':'id'}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320760 entries, 0 to 320759
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   id      320760 non-null  object
dtypes: object(1)
memory usage: 2.4+ MB


In [66]:
entity.glue_train_df[['id_left']].rename(columns={'id_left':'id'}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320760 entries, 0 to 320759
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   id      320760 non-null  object
dtypes: object(1)
memory usage: 2.4+ MB


In [68]:
#entity.glue_train_df[['id_left']].rename(columns={'id_left':'id'}).join(entity.glue_train_df[['id_right']].rename(columns={'id_right':'id'}), on='id')

In [103]:
a=entity.glue_train_df
a['id_left'] = a['id_left'].astype(str)
a['id_right'] = a['id_right'].astype(str)

In [74]:
a.merge(a, left_on='id_left', right_on='id_right')

id_left_x id_right_x  \
0         422862      96457   
1         422862      96457   
2         147570        787   
3         147570     114122   
4          37932     371478   
...          ...        ...   
252202    353923     434187   
252203    446140     284801   
252204    379402     271315   
252205    136002     136003   
252206    122541      20255   

                                              text_left_x  \
0                          How is air traffic controlled?   
1                          How is air traffic controlled?   
2       What is the best self help book you have read?...   
3       What is the best self help book you have read?...   
4       Do you need a passport to go to Jamaica from t...   
...                                                   ...   
252202            Why would my laptop not be turning off?   
252203  What are some fun things to do/ must see thing...   
252204                      Which is better, SLR or DSLR?   
252205  How can I send money from my debit card to ano...   
252206                               What are the trolls?   

                                             text_right_x  label_x id_left_y  \
0            How do you become an air traffic controller?        0     96458   
1            How do you become an air traffic controller?        0    422861   
2         What are the top self help books I should read?        1    147569   
3       Which is the best self help book you've ever r...        1    147569   
4                              How can I move to Jamaica?        0    360877   
...                                                   ...      ...       ...   
252202    How can I turn off my laptop screen completely?        0    181260   
252203  What are some good things to do in Phuket Thai...        1    284800   
252204  Should beginning photographers purchase an SLR...        0    379401   
252205  I need to send money now from debit to debit. ...        0     58820   
252206                        How do trolls troll trolls?        0    511657   

       id_right_y                                        text_left_y  \
0          422862     How does one become an air traffic controller?   
1          422862                       What is Air Traffic Control?   
2          147570  What are some of the best self help books out ...   
3          147570  What are some of the best self help books out ...   
4           37932           Is a passport required to go to Jamaica?   
...           ...                                                ...   
252202     353923                   Why is my laptop not turning on?   
252203     446140       Which things I must do in phuket (thailand)?   
252204     379402                                Slr or DSLR better?   
252205     136002  How can you transfer money from a debit card t...   
252206     122541            What is it that you do to troll people?   

                                             text_right_y  label_y  
0                          How is air traffic controlled?        0  
1                          How is air traffic controlled?        0  
2       What is the best self help book you have read?...        1  
3       What is the best self help book you have read?...        1  
4       Do you need a passport to go to Jamaica from t...        0  
...                                                   ...      ...  
252202            Why would my laptop not be turning off?        0  
252203  What are some fun things to do/ must see thing...        1  
252204                      Which is better, SLR or DSLR?        1  
252205  How can I send money from my debit card to ano...        0  
252206                               What are the trolls?        0  

[252207 rows x 10 columns]

In [36]:
print(entity.glue_train_df.iloc[0,2])
print(simple_preproc(entity.glue_train_df.iloc[0,2]))

How is the life of a math student? Could you describe your own experiences?
['how', 'is', 'the', 'life', 'of', 'a', 'math', 'student', 'could', 'you', 'describe', 'your', 'own', 'experiences']


In [38]:
entity.glue_train_df['text_left'].apply(lambda x: simple_preproc(x))

0         [how, is, the, life, of, a, math, student, cou...
1                [how, do, i, control, my, horny, emotions]
2         [what, causes, stool, color, to, change, to, y...
3                         [what, can, one, do, after, mbbs]
4         [where, can, i, find, a, power, outlet, for, m...
                                ...                        
320755    [why, might, a, girl, feel, bad, when, she, ge...
320756    [have, the, ancient, mayans, been, scientifica...
320757    [what, is, the, best, solution, to, the, kashm...
320758    [are, there, any, free, public, company, finan...
320759    [what, are, the, top, books, that, teach, andr...
Name: text_left, Length: 320760, dtype: object

In [126]:
def get_all_tokens(list_of_df: List[pd.DataFrame], min_occurancies: int) -> List[str]:
    union_df = pd.DataFrame(columns=['id', 'text'])
    for df in list_of_df:
        for text_col, id_col in zip (['text_left', 'text_right'],
                                     ['id_left', 'id_right']):
            curr_df = df[[id_col, text_col]]
            curr_df.columns = ['id', 'text']
            union_df = pd.concat([union_df, curr_df], axis=0)
    union_df = union_df.drop_duplicates('id')
    union_df['words_list'] = union_df['text'].apply(lambda x: simple_preproc(x))
    vocab = pd.Series([word for doc in union_df['words_list'] for word in doc])
    vocab = vocab.value_counts().to_dict()
    filtered_vocab = _filter_rare_words(vocab=vocab, min_occurancies=min_occurancies)
    return filtered_vocab

def _filter_rare_words(vocab: Dict[str, int], min_occurancies: int) -> Dict[str, int]:
    return dict((k, v) for k, v in vocab.items() if v >= min_occurancies)

In [127]:
%%time
a  = get_all_tokens([entity.glue_train_df, entity.glue_dev_df], min_occurancies=1)

CPU times: user 1min 55s, sys: 232 ms, total: 1min 55s
Wall time: 1min 55s


In [131]:
#entity.all_tokens

# 2

In [4]:
glove_vectors_path='data/glove.6B.50d.txt'

In [5]:
glove_embeddings = {}
with open(glove_vectors_path,'r') as f:
    for line in f:
        split_line = line.split()
        word = split_line[0]
        embedding = np.array(split_line[1:], dtype=str)
        glove_embeddings[word] = embedding

In [ ]:
#glove_embeddings

In [3]:
matrix, vocab, unk_words = entity.create_glove_emb_from_file(file_path='data/glove.6B.50d.txt', inner_keys=entity.all_tokens, random_seed=entity.random_seed, rand_uni_bound=entity.emb_rand_uni_bound)

In [44]:
#np.random.seed(random_seed)
#glove_embeddings = self._read_glove_embeddings(file_path=file_path)
glove_embeddings = entity._read_glove_embeddings(file_path=file_path)

#glove_words = [key for key in glove_embeddings]

matrix = np.array([value for key,value in glove_embeddings.items()], dtype=float)
vocab = {key: i for i,key in enumerate(glove_embeddings)}

index = [vocab[key] for key in inner_keys if key in vocab.keys()]
words = [key for key in inner_keys if key in vocab.keys()]
unk_words = ['PAD', 'OOV'] + [key for key in inner_keys if key not in vocab.keys()]

emb_size = next(iter(glove_embeddings.values())).shape[0]
mask_matrix = np.zeros((2, emb_size))
unk_words_matrix = np.random.uniform(low=-rand_uni_bound, high=rand_uni_bound, size=(len(unk_words) - 2, emb_size))
words_matrix = np.array([value for key,value in glove_embeddings.items()], dtype=float)
matrix = np.concatenate((mask_matrix, unk_words_matrix, words_matrix))

vocab = {key: i for i,key in enumerate(unk_words)}
vocab.update({key: i+len(vocab) for i,key in enumerate(words)})

In [6]:
file_path='data/glove.6B.50d.txt'
inner_keys=entity.all_tokens
rand_uni_bound=entity.emb_rand_uni_bound

In [41]:
glove_embeddings = entity._read_glove_embeddings(file_path=file_path)

#glove_words = [key for key in glove_embeddings]

matrix = np.array([value for key,value in glove_embeddings.items()], dtype=float)
vocab = {key: i for i,key in enumerate(glove_embeddings)}

index = [vocab[key] for key in inner_keys if key in vocab.keys()]
words = [key for key in inner_keys if key in vocab.keys()]

In [33]:
matrix = matrix[index]

In [46]:
len(vocab)

83011

In [47]:
len(unk_words)

24106

In [48]:
24106/83011

0.2903952488224452

In [8]:
emb_size=50

In [15]:
#np.zeros((2,50))

# 3

In [5]:
x = np.array([0.1,0,-0.05])
mu=0
sigma=1

distances = np.sum((x[:, np.newaxis] - mu) ** 2, axis=-1)
kernel_matrix = np.exp(-distances / (2 * sigma ** 2))

In [5]:
matrix, _, __ = entity.create_glove_emb_from_file(file_path='data/glove.6B.50d.txt', inner_keys=entity.all_tokens, random_seed=entity.random_seed, rand_uni_bound=entity.emb_rand_uni_bound)

In [7]:
len(_)

83011

In [8]:
matrix.shape

(83011, 50)

In [9]:
x[:, np.newaxis] 

array([[ 0.1 ],
       [ 0.  ],
       [-0.05]])

knrm = KNRM(embedding_matrix=matrix, freeze_embeddings=True)

In [10]:
kernel_num = 11
if kernel_num % 2 == 1:
    n = (kernel_num - 1) * 2 + 1
    kernel_list = np.linspace(-1, 1, num=n)
    kernel_list = [round(val, 2) for i, val in enumerate(kernel_list) if i % 2 == 1] + [round(kernel_list[-1], 2)]

In [18]:
kernel_list

array([-0.9, -0.7, -0.5, -0.3, -0.1,  0.1,  0.3,  0.5,  0.7,  0.9,  0. ])

In [19]:
exact_sigma = .1

In [20]:
kernel_list = np.concatenate([np.linspace(-1 + exact_sigma, 1 - exact_sigma, num=kernel_num - 1), [0]])

In [21]:
kernel_list

array([-0.9, -0.7, -0.5, -0.3, -0.1,  0.1,  0.3,  0.5,  0.7,  0.9,  0. ])

In [ ]:
out_layers = [10,5]

In [ ]:
modules = []   
if len(out_layers) == 0:
    modules.append(torch.nn.Linear(kernel_num, 1))
else:
    i_prev = kernel_num
    for i in out_layers:
        modules.append(torch.nn.ReLU())
        modules.append(torch.nn.Linear(i_prev, i))  
        i_prev = i
    modules.append(torch.nn.ReLU())
    modules.append(torch.nn.Linear(i, 1))

sequential = torch.nn.Sequential(*modules)

In [28]:
sequential

Sequential(
  (0): ReLU()
  (1): Linear(in_features=11, out_features=10, bias=True)
  (2): ReLU()
  (3): Linear(in_features=10, out_features=5, bias=True)
  (4): ReLU()
  (5): Linear(in_features=5, out_features=1, bias=True)
)

In [28]:
a = entity.glue_train_df

In [33]:
query, doc = a['text_left'][:2].apply(lambda x: entity.simple_preproc(x)), a['text_right'][:2].apply(lambda x: entity.simple_preproc(x))

In [54]:
query

0    [how, is, the, life, of, a, math, student, cou...
1           [how, do, i, control, my, horny, emotions]
Name: text_left, dtype: object

In [55]:
a

id_left id_right                                          text_left  \
0       213221   213222  How is the life of a math student? Could you d...   
1       536040   536041                How do I control my horny emotions?   
2       364011   490273       What causes stool color to change to yellow?   
3       155721     7256                        What can one do after MBBS?   
4       279958   279959  Where can I find a power outlet for my laptop ...   
...        ...      ...                                                ...   
320755  145775   145776  Why might a girl feel bad when she gets a love...   
320756   12956    12957  Have the Ancient Mayans been scientifically te...   
320757   29399   168598  What is the best solution to the Kashmir confl...   
320758   38855    38856  Are there any free public company financial da...   
320759  244865   244866  What are the top books that teach Android eCom...   

                                               text_right  label  
0       Which level of prepration is enough for the ex...      0  
1                      How do you control your horniness?      1  
2       What can cause stool to come out as little balls?      0  
3                            What do i do after my MBBS ?      1  
4       Would a second airport in Sydney, Australia be...      0  
...                                                   ...    ...  
320755  Should a girl share intimate feelings with her...      0  
320756  Has Ancient Mesopotamia been scientifically te...      1  
320757          What is the solution of Kashmir conflict?      1  
320758  What are the distinguishing features between k...      0  
320759  What are the top books that teach iOS eCommerc...      0  

[320760 rows x 5 columns]

In [35]:
a['text_left'][:2].apply(lambda x: entity.simple_preproc(x))

0    [how, is, the, life, of, a, math, student, cou...
1           [how, do, i, control, my, horny, emotions]
Name: text_left, dtype: object

In [51]:
knrm = KNRM(embedding_matrix = matrix, freeze_embeddings=True)

mu==1


In [10]:
embeddings = knrm.embeddings

In [34]:
knrm._get_mlp()

Sequential(
  (0): ReLU()
  (1): Linear(in_features=21, out_features=10, bias=True)
  (2): ReLU()
  (3): Linear(in_features=10, out_features=5, bias=True)
  (4): ReLU()
  (5): Linear(in_features=5, out_features=1, bias=True)
)

In [35]:
knrm._apply_kernels()

TypeError: _apply_kernels() missing 1 required positional argument: 'matching_matrix'

In [18]:
len(knrm.out_layers)

2

In [19]:
model, vocab, unk_words = entity.build_knrm_model()

In [1]:
model

NameError: name 'model' is not defined

In [2]:
np.concatenate([np.linspace(-1 + knrm.exact_sigma, 1 - knrm.exact_sigma, num=knrm.kernel_num - 1), [0]])

NameError: name 'np' is not defined

In [22]:
kernels = torch.nn.ModuleList()
# допишите ваш код здесь
kernel_list = np.concatenate([np.linspace(-1 + knrm.exact_sigma, 1 - knrm.exact_sigma, num=knrm.kernel_num - 1), [1]])
for mu in kernel_list:
    kernel = GaussianKernel(mu=mu, sigma=knrm.sigma)
    kernels.append(kernel)

In [25]:
GaussianKernel(mu=mu, sigma=knrm.sigma)

GaussianKernel()

In [58]:
#for i in range(len(query)):
query_emb = torch.stack([
    torch.stack([embeddings.weight[entity.vocab[word]] for word in query[i]]) 
    for q in query
])
doc_emb = torch.stack([
    torch.stack([embeddings.weight[entity.vocab[word]] for word in doc[i]])
    for d in doc
])

In [ ]:
knrm.predict({'query': a['text_left'][:2].apply(lambda x: entity.simple_preproc(x)), 'document': a['text_right'][:2].apply(lambda x: entity.simple_preproc(x))})

In [59]:
query_emb.shape

torch.Size([2, 14, 50])

In [60]:
doc_emb.shape

torch.Size([2, 10, 50])

In [63]:
query_emb[None,:,:].shape

torch.Size([1, 2, 14, 50])

In [67]:
doc_emb[:,:,None,:].shape

torch.Size([2, 10, 1, 50])

In [69]:
F.cosine_similarity(query_emb[:,:,None,:], doc_emb[:,None,:,:], dim=-1).shape

torch.Size([2, 14, 10])

In [71]:
#entity.build_knrm_model()

In [35]:
entity.dev_pairs_for_ndcg[:5]

[['100141', '75743', 2],
 ['100141', '100142', 2],
 ['100141', '525228', 0],
 ['100141', '160860', 0],
 ['100141', '205882', 0]]

In [38]:
entity.idx_to_text_mapping_train['213221']

'How is the life of a math student? Could you describe your own experiences?'

In [39]:
entitydev_pairs_for_ndcg

NameError: name 'dev_pairs_for_ndcg' is not defined

In [ ]:
query_emb = torch.stack([
            torch.stack([self.embeddings.weight[entity.vocab[word]] for word in q]) 
            for q in query
        ])

In [40]:
knrm.embeddings.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0195,  0.0861,  0.0411,  ..., -0.1484, -0.0738, -0.0545],
        ...,
        [-0.3321,  0.5584,  0.4364,  ...,  0.9613, -0.5368,  0.0657],
        [ 2.0335,  0.4762, -0.8951,  ..., -0.2898, -0.3793, -0.0756],
        [ 0.4789, -0.0984, -0.2946,  ...,  0.2410,  0.4327, -0.8582]])

In [ ]:
[knrm.embeddings.weight[entity.vocab[word]] for word in q]

# 4

In [7]:
val_dataset = ValPairsDataset(entity.dev_pairs_for_ndcg,
              entity.idx_to_text_mapping_dev,
              vocab=entity.vocab, oov_val=entity.vocab['OOV'],
              preproc_func=entity.simple_preproc)

In [82]:
len(entity.dev_pairs_for_ndcg)

31095

In [36]:
#entity.idx_to_text_mapping_dev

In [32]:
val_dataset

In [23]:
val_dataset.index_pairs_or_triplets[5555]

[14659, 239068, 0]

In [24]:
val_dataset.index_pairs_or_triplets[5557]

[14659, 351703, 0]

In [25]:
val_dataset.__getitem__(5555)

({'query': [24107,
   24108,
   24106,
   25082,
   24170,
   24111,
   24138,
   24109,
   24867,
   24329,
   24112,
   24106,
   24211,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0],
  'document': [24113,
   24119,
   24110,
   26784,
   24123,
   25183,
   25237,
   24150,
   24476,
   24617,
   24149,
   25849,
   24122,
   34569,
   24110,
   24163,
   25179,
   24112,
   33022,
   24112,
   59190,
   39046,
   24248,
   24286,
   26606,
   25237,
   25939,
   0,
   0,
   0]},
 0)

In [26]:
entity.vocab['OOV']

1

In [39]:
val_dataset.index_pairs_or_triplets[0]

['100141', '75743', 2]

In [27]:
print(val_dataset)

In [19]:
(val_dataset._convert_text_idx_to_token_idxs(5557))

[24161,
 24119,
 24110,
 24138,
 24135,
 37531,
 26423,
 24737,
 24112,
 25118,
 24118,
 25282,
 27255,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [160]:
np.concatenate([np.linspace(-1, 1, num=11*2), [1]])

array([-1.        , -0.9047619 , -0.80952381, -0.71428571, -0.61904762,
       -0.52380952, -0.42857143, -0.33333333, -0.23809524, -0.14285714,
       -0.04761905,  0.04761905,  0.14285714,  0.23809524,  0.33333333,
        0.42857143,  0.52380952,  0.61904762,  0.71428571,  0.80952381,
        0.9047619 ,  1.        ,  1.        ])

In [ ]:
[-0.9, -0.7, -0.5, -0.3, -0.1, 0.1, 0.3, 0.5, 0.7, 0.9, 1].

In [181]:
np.concatenate([[val for i, val in enumerate(np.linspace(-1, 1, num=11+10)) if i%2==1], [1]])

array([-0.9, -0.7, -0.5, -0.3, -0.1,  0.1,  0.3,  0.5,  0.7,  0.9,  1. ])

In [94]:
i=0
for batch in (entity.val_dataloader):
    inp_1, y = batch
    
    #print(inp_1)
    preds = knrm.predict(inp_1)
    if i ==0:
        break
    preds_np = preds.detach().numpy()
    all_preds.append(preds_np)

out torch.Size([1024])


In [98]:
#list(preds)

In [188]:
inp_1

{'query': tensor([[24107, 24116, 24106,  ..., 24112, 24575,     0],
         [24107, 24116, 24106,  ..., 24112, 24575,     0],
         [24107, 24116, 24106,  ..., 24112, 24575,     0],
         ...,
         [24107, 24119, 24131,  ...,     0,     0,     0],
         [24107, 24119, 24131,  ...,     0,     0,     0],
         [24107, 24119, 24131,  ...,     0,     0,     0]]),
 'document': tensor([[24107, 24116, 24106,  ..., 24112, 28627,     0],
         [24107, 24116, 24106,  ..., 24112, 31270,     0],
         [24113, 24115, 24110,  ...,     0,     0,     0],
         ...,
         [24107, 24128, 24106,  ...,     0,     0,     0],
         [24113, 24119, 24157,  ...,     0,     0,     0],
         [24107, 24116, 24136,  ...,     0,     0,     0]])}

In [10]:
query, doc = inp_1['query'], inp_1['document']
matching_matrix = knrm._get_matching_matrix(query, doc)

In [ ]:
knrm.embeddings.weight

In [26]:
query[0]

tensor([24107, 24116, 24106, 25005, 24111, 24267, 24140, 25255, 24139, 24109,
        24296, 24539, 24111, 24109, 24866, 24329, 24112, 24106, 24211, 24113,
        24115, 24168, 24439, 24111, 24106, 26243, 25005, 24112, 24575,     0])

In [25]:
list(entity.vocab.keys())[24107]

'what'

In [61]:
[list(entity.vocab.keys())[i] for i in query[0]]

['what',
 'are',
 'the',
 'laws',
 'to',
 'change',
 'your',
 'status',
 'from',
 'a',
 'student',
 'visa',
 'to',
 'a',
 'green',
 'card',
 'in',
 'the',
 'us',
 'how',
 'do',
 'they',
 'compare',
 'to',
 'the',
 'immigration',
 'laws',
 'in',
 'canada',
 'PAD']

In [65]:
for j in range(10):
    print(' '.join([list(entity.vocab.keys())[i] for i in doc[j]]))

what are the laws to change your status from a student visa to a green card in the us how do they compare to the immigration laws in argentina PAD
what are the laws to change your status from a student visa to a green card in the us how do they compare to the immigration laws in chile PAD
how do i find a percentage of two numbers PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD
what causes shoulder pain to be worse at night PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD
what is a hypertonic solution what are some examples PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD
what is a good comeback when a girl calls you handsome and you re a girl PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD
i ’ m excelling at my job and i ’ m still not getting promoted what should i do PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD PAD
is it right to leave your parents for love PAD PAD PAD PAD PAD 

In [96]:
for j in range(10):
    print(' '.join([list(entity.vocab.keys())[i] for i in query[j]]))

what are the laws to change your status from a student visa to a green card in the us how do they compare to the immigration laws in canada PAD
what are the laws to change your status from a student visa to a green card in the us how do they compare to the immigration laws in canada PAD
what are the laws to change your status from a student visa to a green card in the us how do they compare to the immigration laws in canada PAD
what are the laws to change your status from a student visa to a green card in the us how do they compare to the immigration laws in canada PAD
what are the laws to change your status from a student visa to a green card in the us how do they compare to the immigration laws in canada PAD
what are the laws to change your status from a student visa to a green card in the us how do they compare to the immigration laws in canada PAD
what are the laws to change your status from a student visa to a green card in the us how do they compare to the immigration laws in can

In [34]:
matrix[24107]

array([ 0.45323 ,  0.059811, -0.10577 , -0.333   ,  0.72359 , -0.08717 ,
       -0.61053 , -0.037695, -0.30945 ,  0.21805 , -0.43605 ,  0.47318 ,
       -0.76866 , -0.2713  ,  1.1042  ,  0.59141 ,  0.56962 , -0.18678 ,
        0.14867 , -0.67292 , -0.34672 ,  0.52284 ,  0.22959 , -0.072014,
        0.93967 , -2.3985  , -1.3238  ,  0.28698 ,  0.75509 , -0.76522 ,
        3.3425  ,  0.17233 , -0.51803 , -0.8297  , -0.29333 , -0.50076 ,
       -0.15228 ,  0.098973,  0.18146 , -0.1742  , -0.40666 ,  0.20348 ,
       -0.011788,  0.48252 ,  0.024598,  0.34064 , -0.084724,  0.5324  ,
       -0.25103 ,  0.62546 ])

In [67]:
matching_matrix[2]

tensor([[0.9634, 0.8908, 0.8926, 0.8847, 0.6997, 0.3026, 0.6849, 0.5669, 0.6352,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000],
        [0.7968, 0.7752, 0.6204, 0.7838, 0.5729, 0.3908, 0.7279, 0.7870, 0.7672,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000],
        [0.6770, 0.6325, 0.6265, 0.6602, 0.8517, 0.3446, 0.9026, 0.8052, 0.6497,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000],
        [0.5102, 0.5174, 0.3409, 0.4233, 0.4424, 0.2618, 0.5438, 0.3996, 0.4108,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
       

In [36]:
query_emb  = torch.stack([
            torch.stack([knrm.embeddings.weight[idx] for idx in q]) 
            for q in query
        ])#[:,:,None,:]#.shape
doc_emb  = torch.stack([
            torch.stack([knrm.embeddings.weight[idx] for idx in q]) 
            for q in doc
        ])#[:,:,None,:]#.shape

In [37]:
query_emb

tensor([[[ 0.4532,  0.0598, -0.1058,  ...,  0.5324, -0.2510,  0.6255],
         [ 0.9619,  0.0125,  0.2173,  ...,  0.1403, -0.3847, -0.3871],
         [ 0.4180,  0.2497, -0.4124,  ..., -0.1841, -0.1151, -0.7858],
         ...,
         [ 0.3304,  0.2500, -0.6087,  ..., -0.5070, -0.0273, -0.5329],
         [-0.7249,  0.4052, -0.3589,  ..., -0.1103,  0.0151, -0.0369],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[ 0.4532,  0.0598, -0.1058,  ...,  0.5324, -0.2510,  0.6255],
         [ 0.9619,  0.0125,  0.2173,  ...,  0.1403, -0.3847, -0.3871],
         [ 0.4180,  0.2497, -0.4124,  ..., -0.1841, -0.1151, -0.7858],
         ...,
         [ 0.3304,  0.2500, -0.6087,  ..., -0.5070, -0.0273, -0.5329],
         [-0.7249,  0.4052, -0.3589,  ..., -0.1103,  0.0151, -0.0369],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[ 0.4532,  0.0598, -0.1058,  ...,  0.5324, -0.2510,  0.6255],
         [ 0.9619,  0.0125,  0.2173,  ...,  0

In [43]:
#matching_matrix[0]

In [72]:
matching_matrix[2][None, ].shape

torch.Size([1, 30, 30])

In [87]:
torch.exp(-distances / (2 * 0.1 ** 2))

tensor([[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]])

In [90]:
-distances / (2 * 0.1 ** 2)

tensor([[[-2162.1350],
         [-2040.1750],
         [-2082.7700],
         [-1741.3251],
         [-2163.2600],
         [-2090.4050],
         [-1993.7651],
         [-1794.0100],
         [-2074.0549],
         [-2054.4001],
         [-1787.6200],
         [-1577.0150],
         [-2163.2600],
         [-2054.4001],
         [-1806.1400],
         [-1752.8700],
         [-2071.1799],
         [-2082.7700],
         [-1949.4900],
         [-2140.7852],
         [-2088.2151],
         [-2178.5852],
         [-1819.0551],
         [-2163.2600],
         [-2082.7700],
         [-1706.9651],
         [-1741.3251],
         [-2071.1799],
         [-1730.4751],
         [-1353.7501]]])

In [85]:
distances = torch.tensor([[[43.2427],
         [40.8035],
         [41.6554],
         [34.8265],
         [43.2652],
         [41.8081],
         [39.8753],
         [35.8802],
         [41.4811],
         [41.0880],
         [35.7524],
         [31.5403],
         [43.2652],
         [41.0880],
         [36.1228],
         [35.0574],
         [41.4236],
         [41.6554],
         [38.9898],
         [42.8157],
         [41.7643],
         [43.5717],
         [36.3811],
         [43.2652],
         [41.6554],
         [34.1393],
         [34.8265],
         [41.4236],
         [34.6095],
         [27.0750]]])

In [93]:
KM = []
for kernel in knrm.kernels:
    # shape = [B]
    K = torch.log1p(kernel(matching_matrix[3][None, ]).sum(dim=-1)).sum(dim=-1)
    KM.append(K)

tensor([[[5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3050e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [5.3049e-19],
         [7.5785e-19]]])
tensor([[[4.2986e-15],
         [4.2986e-15],
         [4.2986e-15],
         [4.2986e-15],
         [4.2986e-15],
         [4.2986e-15],
         [4.2986e-15],
         [4.2986e-15],
         [4.2986e-15],
         [4.2986e-15],
         [4.2986e-15],
         [4.2987e-15],
         [4.2986e-15],
         

In [78]:
KM

[tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([1.9271e-41]),
 tensor([2.2007e-15]),
 tensor([0.0232]),
 tensor([0.0232]),
 tensor([1.6449e-13]),
 tensor([1.5971e-29]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.])]

In [80]:
KM

[tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([1.9271e-41]),
 tensor([2.2007e-15]),
 tensor([0.0232]),
 tensor([0.0232]),
 tensor([1.2993e-14]),
 tensor([7.3139e-32]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.]),
 tensor([0.])]

In [ ]:
distances = ((x[:, :, None]  - self.mu) ** 2).sum(-1)

In [47]:
kernel.forward(matching_matrix).sum(dim=-1)

kernel_matrix torch.Size([1024, 30, 1])


tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [58]:
query_emb[0]

tensor([[ 0.4532,  0.0598, -0.1058,  ...,  0.5324, -0.2510,  0.6255],
        [ 0.9619,  0.0125,  0.2173,  ...,  0.1403, -0.3847, -0.3871],
        [ 0.4180,  0.2497, -0.4124,  ..., -0.1841, -0.1151, -0.7858],
        ...,
        [ 0.3304,  0.2500, -0.6087,  ..., -0.5070, -0.0273, -0.5329],
        [-0.7249,  0.4052, -0.3589,  ..., -0.1103,  0.0151, -0.0369],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]])

In [59]:
doc_emb[0]

tensor([[ 0.4532,  0.0598, -0.1058,  ...,  0.5324, -0.2510,  0.6255],
        [ 0.9619,  0.0125,  0.2173,  ...,  0.1403, -0.3847, -0.3871],
        [ 0.4180,  0.2497, -0.4124,  ..., -0.1841, -0.1151, -0.7858],
        ...,
        [ 0.3304,  0.2500, -0.6087,  ..., -0.5070, -0.0273, -0.5329],
        [ 0.3031, -0.2483, -0.6280,  ..., -0.3413,  0.6022, -0.8492],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]])

In [56]:
list(KM[9])

[tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.0232),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5114),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5346),
 tensor(0.5579),
 tensor(0.5579),
 tensor(0.5579),
 tensor(0.5581),
 tensor(0.5579),
 tensor(0.5579),
 tensor(0.5579),
 tensor(0.5579),
 tensor(0.5579),
 tensor(0.5579),
 tensor(0.5579),
 tensor(0.5579),
 tensor(0.5579),
 tensor(0.5579

In [189]:
matching_matrix = knrm._get_matching_matrix(query, doc)

In [199]:
query_emb  = torch.stack([
            torch.stack([knrm.embeddings.weight[idx] for idx in q]) 
            for q in query
        ])#[:,:,None,:]#.shape
doc_emb  = torch.stack([
            torch.stack([knrm.embeddings.weight[idx] for idx in q]) 
            for q in doc
        ])#[:,:,None,:]#.shape

In [202]:
F.cosine_similarity(query_emb[:,:,None,:], doc_emb[:,None,:,:], dim=-1)#.shape

tensor([[[1.0000, 0.7264, 0.7238,  ..., 0.6513, 0.2725, 0.0000],
         [0.7264, 1.0000, 0.7204,  ..., 0.6695, 0.3298, 0.0000],
         [0.7238, 0.7204, 1.0000,  ..., 0.9029, 0.4303, 0.0000],
         ...,
         [0.6513, 0.6695, 0.9029,  ..., 1.0000, 0.4799, 0.0000],
         [0.3939, 0.4526, 0.5945,  ..., 0.6452, 0.5187, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[1.0000, 0.7264, 0.7238,  ..., 0.6513, 0.2403, 0.0000],
         [0.7264, 1.0000, 0.7204,  ..., 0.6695, 0.3212, 0.0000],
         [0.7238, 0.7204, 1.0000,  ..., 0.9029, 0.4146, 0.0000],
         ...,
         [0.6513, 0.6695, 0.9029,  ..., 1.0000, 0.4975, 0.0000],
         [0.3939, 0.4526, 0.5945,  ..., 0.6452, 0.5190, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.9634, 0.8908, 0.8926,  ..., 0.0000, 0.0000, 0.0000],
         [0.7968, 0.7752, 0.6204,  ..., 0.0000, 0.0000, 0.0000],
         [0.6770, 0.6325, 0.6265,  ..., 0.0000, 0.0000, 0.

In [140]:
kernel = knrm.kernels[10]

In [148]:
kernel(matching_matrix).sum(dim=-1).shape

torch.Size([1, 1024])

In [141]:
query, doc = inp_1['query'], inp_1['document']

In [89]:
knrm.predict(inp_1).shape

torch.Size([1024, 1])

In [29]:
for i in range(5):
    print(doc[i+100])

tensor([24107, 24116, 24136, 24276, 24114, 25987, 24117, 31233, 25051, 24112,
        25377, 24176,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0])
tensor([24107, 24116, 24136, 24276, 24114, 25987, 24117, 31233, 25051, 24112,
        25377, 24176,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0])
tensor([24107, 24116, 24136, 24276, 24114, 25987, 24117, 31233, 25051, 24112,
        25377, 24176,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0])
tensor([24107, 24116, 24136, 24276, 24114, 25987, 24117, 31233, 25051, 24112,
        25377, 24176,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0])
tensor([24107, 24116, 24136, 24276, 24114, 25987, 24117, 312

for i in range(5):
    print(query[i+400])

In [42]:
torch.stack([
            torch.stack([knrm.embeddings.weight[idx] for idx in q]) 
            for q in query
        ])

tensor([[[ 0.4532,  0.0598, -0.1058,  ...,  0.5324, -0.2510,  0.6255],
         [ 0.8052,  0.3712,  0.5593,  ..., -0.1895, -0.2090,  0.4761],
         [ 0.9110, -0.2287,  0.2077,  ...,  0.1669, -0.0501,  0.1924],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[ 0.4532,  0.0598, -0.1058,  ...,  0.5324, -0.2510,  0.6255],
         [ 0.8052,  0.3712,  0.5593,  ..., -0.1895, -0.2090,  0.4761],
         [ 0.9110, -0.2287,  0.2077,  ...,  0.1669, -0.0501,  0.1924],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[ 0.4532,  0.0598, -0.1058,  ...,  0.5324, -0.2510,  0.6255],
         [ 0.8052,  0.3712,  0.5593,  ..., -0

In [134]:
kernel = knrm.kernels[0]

In [54]:
kernel(matching_matrix).sum(dim=-1)

tensor(1.7110e-16)

In [12]:
y.shape

torch.Size([1024])

In [48]:
matching_matrix = knrm._get_matching_matrix(inp_1['query'], inp_1['document'])#.shape

In [77]:
distances = ((x - 0) ** 2)#.sum(dim=-1)
kernel_matrix = np.exp(-distances / (2 * 1 ** 2)).sum(dim=-1)

In [100]:
distances = ((x.unsqueeze(0) - 1) **2).sum(2)#.shape

In [78]:
kernel_matrix.shape

torch.Size([1024, 30])

In [102]:
torch.exp(-distances/ (2 * 1)).shape

torch.Size([1, 1024, 30])

In [122]:
(x.unsqueeze(0)- 0.2).sum(-1).shape

torch.Size([1, 1024, 30])

In [127]:
def forward(x):
    # допишите ваш код здесь
    #distances = np.sum((x[:, np.newaxis] - self.mu) ** 2, axis=-1)
    distances = ((x.unsqueeze(0) - 0) ** 2).sum(-1)
    kernel_matrix = torch.exp(-distances / (2 * 0.01 ** 2))
    return kernel_matrix

In [128]:
forward(x).shape

torch.Size([1, 1024, 30])

In [135]:
matching_matrix = forward(x)
torch.log1p(kernel(matching_matrix).sum(dim=-1)).sum(dim=-1)

tensor([0.])

In [137]:
matching_matrix.shape

torch.Size([1, 1024, 30])

In [7]:
entity.val_dataloader[0]

TypeError: 'DataLoader' object is not subscriptable

In [28]:
val_dataset.__getitem__(5555)

({'query': 14659, 'document': 239068}, 0)

In [36]:
max_len_q1 = -1 
pad_len1 = max_len_q1 - len(left_elem['query'])

In [37]:
int(left_elem['query']) + [0] * pad_len1

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [ ]:
max(len(left_elem['query']), max_len_q1)

In [11]:
left_elem = {'query': '14840', 'document': '57529'}

len(left_elem['query'])

5

In [13]:
left_elem['query'] + [0] * 10

TypeError: can only concatenate str (not "list") to str

In [22]:
entity.glue_train_df[['id_left', 'text_left']]

id_left                                          text_left
0       213221  How is the life of a math student? Could you d...
1       536040                How do I control my horny emotions?
2       364011       What causes stool color to change to yellow?
3       155721                        What can one do after MBBS?
4       279958  Where can I find a power outlet for my laptop ...
...        ...                                                ...
320755  145775  Why might a girl feel bad when she gets a love...
320756   12956  Have the Ancient Mayans been scientifically te...
320757   29399  What is the best solution to the Kashmir confl...
320758   38855  Are there any free public company financial da...
320759  244865  What are the top books that teach Android eCom...

[320760 rows x 2 columns]

In [15]:
x = torch.Tensor([0,1,1])
distances = np.sum((x[:, np.newaxis] - 0) ** 2, axis=-1)

TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=int, ), but expected one of:
 * (*, torch.dtype dtype)
      didn't match because some of the keywords were incorrect: out, axis
 * (tuple of names dim, bool keepdim, *, torch.dtype dtype)
 * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)


In [19]:
(x[:, np.newaxis] - 0) ** 2

tensor([[0.],
        [1.],
        [1.]])

In [ ]:
np.sum((x[:, np.newaxis] - 0) ** 2, axis=-1)

In [21]:
distances = (x[:, np.newaxis] - 0) ** 2
kernel_matrix = np.exp(-distances / (2 * 1 ** 2))

In [23]:
np.sum(kernel_matrix)

TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:
 * (*, torch.dtype dtype)
      didn't match because some of the keywords were incorrect: out, axis
 * (tuple of names dim, bool keepdim, *, torch.dtype dtype)
 * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)


In [24]:
kernel_matrix

tensor([[1.0000],
        [0.6065],
        [0.6065]])

In [25]:
torch.sum(kernel_matrix)

tensor(2.2131)

In [28]:
#entity.create_val_pairs(entity.glue_dev_df)