In [1]:
import numpy as np
a = np.array([1, 1])

In [3]:
b = np.concatenate([np.random.rand(14,2)])

In [89]:
np.linalg.norm(a-b, axis=1)

array([0.63557112, 0.69121926, 1.07529218, 1.11459708, 1.10697105,
       1.11142313, 1.16092606, 0.37838278, 0.20970306, 0.53279204,
       0.26685408, 0.15579975, 0.55003828, 0.92917004])

In [38]:
np.where(np.argsort(distances, axis=0)!=i, np.argsort(distances, axis=0))

ValueError: either both or neither of x and y should be given

In [73]:
from solution_template import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [74]:
from solution_template import *
%load_ext autoreload
%autoreload 2
data = np.concatenate([np.array([[0,0], [1,1], [1,2], [2,1], [3,1], [3,3], [3,-1]]), np.random.rand(14,2)])

In [75]:
num_candidates_for_choice_long = 10
num_edges_long = 5
num_candidates_for_choice_short = 10
num_edges_short = 5

In [51]:
result = {}
for i, point in enumerate(data): 
    distances = distance(point, data)
    candidates = np.argsort(distances, axis=0)

    candidates_long = candidates[-num_candidates_for_choice_long:]
    edges_long = candidates_long[np.random.choice(num_candidates_for_choice_long, num_edges_long)]
    #edges_long = np.unique(edges_long)

    candidates_short = candidates[candidates != i][:num_candidates_for_choice_short]
    edges_short = candidates_short[np.random.choice(num_candidates_for_choice_short, num_edges_short)]
    #edges_short = np.unique(edges_short)

    candidates = np.concatenate([edges_long.flatten(), edges_short.flatten()]).tolist()

    result[i] = candidates

In [60]:
i = 8
point = data[8]
distances = distance(point, data)
candidates = np.argsort(distances, axis=0)

candidates_long = candidates[-num_candidates_for_choice_long:]
edges_long = candidates_long[np.random.choice(num_candidates_for_choice_long, num_edges_long)]
#edges_long = np.unique(edges_long)

candidates_short = candidates[candidates != i][:num_candidates_for_choice_short]
edges_short = candidates_short[np.random.choice(num_candidates_for_choice_short, num_edges_short)]
#edges_short = np.unique(edges_short)

candidates = np.concatenate([edges_long.flatten(), edges_short.flatten()]).tolist()

In [58]:
candidates[:num_candidates_for_choice_short]

[6, 1, 0, 15, 4, 9, 16, 16, 14, 10]

In [102]:
np.random.choice(all_documents.shape[0], 5, replace=False)

array([ 1, 12, 15,  5, 11])

In [106]:
p = [1,2,3]
p+[3,4]

[1, 2, 3, 3, 4]

In [105]:
p

[1, 2, 3, [3, 4]]

In [30]:
l = [1, 2, 3, 4, 6, 7, 10, 17]
l.remove(5)

ValueError: list.remove(x): x not in list

In [5]:
create_sw_graph(data)

{0: [2, 3, 5, 7, 10, 12, 14, 15, 17, 20],
 1: [2, 3, 5, 6, 10, 11, 13, 16, 17, 20],
 2: [0, 3, 4, 5, 6, 12, 13, 16, 17, 18],
 3: [1, 2, 5, 6, 7, 8, 11, 13, 15, 20],
 4: [0, 2, 3, 6, 7, 8, 13, 15, 18, 20],
 5: [1, 3, 6, 7, 8, 12, 13, 14, 15, 20],
 6: [0, 5, 10, 11, 12, 15, 16, 17, 19, 20],
 7: [0, 1, 2, 8, 9, 13, 14, 15, 16, 17],
 8: [1, 2, 4, 7, 10, 11, 12, 14, 16, 17],
 9: [0, 1, 3, 4, 7, 8, 12, 17, 19, 20],
 10: [0, 1, 2, 5, 8, 9, 15, 16, 18, 20],
 11: [1, 3, 4, 6, 8, 10, 14, 15, 18, 19],
 12: [0, 1, 3, 5, 7, 9, 13, 14, 16, 19],
 13: [5, 6, 8, 9, 11, 12, 16, 18, 19, 20],
 14: [2, 3, 6, 7, 8, 9, 11, 12, 15, 18],
 15: [1, 2, 3, 4, 6, 10, 11, 12, 14, 19],
 16: [0, 4, 5, 8, 9, 10, 12, 14, 17, 18],
 17: [0, 1, 2, 3, 9, 10, 12, 15, 18, 19],
 18: [0, 1, 2, 4, 9, 10, 11, 13, 15, 19],
 19: [0, 2, 3, 7, 8, 11, 13, 14, 17, 18],
 20: [0, 1, 4, 7, 13, 14, 16, 17, 18, 19]}

In [78]:
from solution_template import *
%load_ext autoreload
%autoreload 2
data = np.concatenate([np.array([[0,0], [1,1], [1,2], [2,1], [3,1], [3,3], [3,-1]]), np.random.rand(14,2)])

query_point = np.array([1,1])

all_documents = data

graph_edges = create_sw_graph(data)

In [9]:
search_k= 10
num_start_points= 5

In [100]:
k_neighbors = set()
for i in range(num_start_points):
    #print('new',i)
    entry_point = np.random.choice(all_documents.shape[0], 1)[0]
    #print(entry_point)
    new_point = entry_point
    prev_point=-1
    #candidates = []
    while prev_point!=new_point:
        point_edges = graph_edges[new_point]
        distances = distance(query_point, data[point_edges])
        prev_point = new_point
        new_point = entry_point_edges[np.argmin(distances)]
        #print(new_point)
        #candidates.append(new_point)
        
        #print(candidates)
    k_neighbors.add(new_point)

k_neighbors = list(k_neighbors)
distances = distance(query_point, data[k_neighbors])
k_neighbors_idx = np.argsort(distances, axis=0)[:search_k]#.flatten().tolist()

[k_neighbors[i[0]] for i in k_neighbors_idx]
#k_neighbors[k_neighbors_idx]

[2, 3]

In [101]:
len(k_neighbors)

2

In [44]:
new_point = entry_point_edges[np.argmin(distances)]
new_point_edges = graph_edges[new_point]
new_point_distances = distance(query_point, data[new_point_edges])

In [45]:
new_point_distances

array([[1.41421356],
       [0.        ],
       [1.        ],
       [2.82842712],
       [1.32148394],
       [0.32803136],
       [0.43967611],
       [1.02699314],
       [0.54295864],
       [1.32992921]])

In [35]:
entry_point_edges

[2, 3, 4, 7, 8, 9, 11, 12, 14, 19]

In [39]:
data[new_point][:, np.newaxis]

array([0.51397018, 0.81289766])

In [95]:
np.sort(distances, axis=0)[-4:]

array([[0.        ],
       [0.1617946 ],
       [0.1831922 ],
       [0.23924253],
       [0.25145912],
       [0.29648633],
       [0.47138888],
       [0.49596236],
       [0.51434038],
       [0.52503103],
       [0.59179443],
       [0.7212111 ],
       [0.77449469],
       [0.78419802]])

In [98]:
np.sort(distances, axis=0)[:4][1:]

array([[0.1617946 ],
       [0.1831922 ],
       [0.23924253]])

In [62]:
result

{0: [2, 5, 7, 9, 11, 15],
 1: [1, 2, 4, 5, 8, 11, 14, 16],
 2: [2, 3, 4, 5, 6, 7, 10],
 3: [0, 2, 3, 5, 6, 7, 9],
 4: [1, 2, 5, 7, 8, 11, 12],
 5: [4, 8, 11, 12, 16],
 6: [2, 3, 5, 6, 9, 11, 16],
 7: [4, 5, 6, 7, 10, 15],
 8: [1, 2, 5, 7, 8, 14, 16],
 9: [0, 2, 3, 9, 10, 11],
 10: [0, 2, 3, 7, 9, 10],
 11: [8, 13, 6, 7],
 12: [4, 5, 6, 8, 10, 11, 12, 16],
 13: [1, 4, 5, 7, 13, 14, 16],
 14: [2, 4, 8, 11, 13, 14],
 15: [8, 9, 11, 15],
 16: [2, 5, 7, 8, 11, 12, 16]}

In [63]:
create_sw_graph(d)

{0: [0, 3, 5, 7, 9, 11],
 1: [1, 2, 5, 8, 11, 12, 14],
 2: [5, 6, 7, 8, 12, 13, 15],
 3: [0, 5, 6, 7, 9, 15],
 4: [2, 4, 5, 8, 11, 14, 16],
 5: [5, 6, 7, 8, 11, 12, 13, 15],
 6: [2, 5, 7, 10, 11, 15],
 7: [2, 5, 6, 11, 15, 16],
 8: [2, 4, 7, 12, 13, 14, 16],
 9: [0, 2, 9, 10, 11, 15],
 10: [0, 2, 5, 7, 9, 15],
 11: [2, 5, 7, 8, 11, 12, 15],
 12: [2, 5, 7, 12, 16],
 13: [2, 4, 5, 11, 16],
 14: [2, 4, 5, 8, 11, 12, 14],
 15: [5, 9, 10, 11, 15, 16],
 16: [2, 4, 5, 7, 8, 11, 13]}

In [26]:
np.sort(data, axis=0)[:num_candidates_for_choice_long]

array([[0.        ],
       [0.28074532],
       [0.31660972],
       [0.35692959],
       [0.53173035],
       [0.63162659],
       [0.7432584 ],
       [0.77006846],
       [0.790732  ],
       [0.79639358]])

In [29]:
candidates_long = np.argsort(data, axis=0)[:num_candidates_for_choice_long]
candidates_long

array([[ 0],
       [ 9],
       [ 3],
       [10],
       [ 6],
       [15],
       [ 7],
       [ 2],
       [11],
       [ 5]])

In [33]:
edges_long = candidates_long[np.random.choice(num_candidates_for_choice_long, num_edges_long)]
edges_long

array([[ 7],
       [ 9],
       [ 7],
       [11],
       [ 5]])

In [50]:
k_neighbors = []
entry_points = np.random.choice(all_documents.shape[0], num_start_points, replace=False)
for i in range(num_start_points):
    print('new',i)
    entry_point = entry_points[i]
    print(entry_point)
    new_point = entry_point
    prev_point=-1
    candidates = [new_point]
    while prev_point!=new_point:
        #print(candidates)
        point_edges = graph_edges[new_point]
        #print(point_edges + [new_point])
        distances = distance(query_point, all_documents[point_edges + [new_point]])
        prev_point = new_point
        new_point = (point_edges + [new_point])[np.argmin(distances)]
        #print(new_point)
        candidates.append(new_point)

        #print(candidates)
    print(candidates, candidates[-3:-1])
    k_neighbors+=candidates[-3:-1]
    #print(k_neighbors)

new 0
19
[19, 15, 1, 1] [15, 1]
new 1
2
[2, 1, 1] [2, 1]
new 2
18
[18, 1, 1] [18, 1]
new 3
13
[13, 1, 1] [13, 1]
new 4
9
[9, 1, 1] [9, 1]


In [53]:
np.array([1,2,3]) + np.array([5,6])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [19]:
i=0
entry_point = entry_points[i]
entry_point
new_point = entry_point

In [22]:
candidates = []

In [34]:
point_edges = graph_edges[new_point]
distances = distance(query_point, all_documents[point_edges])
prev_point = new_point
new_point = point_edges[np.argmin(distances)]
candidates.append(new_point)

In [37]:
candidates + [new_point]

[15, 1, 17, 20, 1, 17, 20, 20]

In [36]:
point_edges

[2, 3, 9, 10, 11, 12, 13, 16, 19, 20]

In [79]:
nsw(query_point, all_documents, graph_edges)

[14]
[14, 1]
[14, 1] 
_______________
[5]
[5, 16]
[5, 16, 8]
[14, 1, 5, 16, 8] 
_______________
[13]
[13, 15]
[13, 15, 10]
[14, 1, 5, 16, 8, 13, 15, 10] 
_______________
[20]
[20, 17]
[14, 1, 5, 16, 8, 13, 15, 10, 20, 17] 
_______________
[7]
[7, 19]
[14, 1, 5, 16, 8, 13, 15, 10, 20, 17, 7, 19] 
_______________


[1, 8, 10, 16, 15, 17, 19, 20, 14, 7]

In [ ]:
query_point

In [56]:
def nsw(query_point: np.ndarray, all_documents: np.ndarray, 
        graph_edges: Dict[int, List[int]],
        search_k: int = 10, num_start_points: int = 5,
        dist_f: Callable = distance) -> np.ndarray:
    # допишите ваш код здесь 
    k_neighbors = []
    entry_points = np.random.choice(all_documents.shape[0], num_start_points, replace=False)
    for i in range(num_start_points):
        #print('new',i)
        entry_point = entry_points[i]
        #print(entry_point)
        new_point = entry_point
        prev_point=-1
        candidates = [new_point]
        while prev_point!=new_point:
            print(candidates)
            point_edges = graph_edges[new_point]
            distances = dist_f(query_point, all_documents[point_edges + [new_point]])
            prev_point = new_point
            new_point = (point_edges + [new_point])[np.argmin(distances)]
            #print(new_point)
            candidates.append(new_point)

            #print(candidates)
        k_neighbors+=candidates[-3:-1]
        print(k_neighbors)

    k_neighbors = list(set(k_neighbors))
    distances = dist_f(query_point, all_documents[k_neighbors])
    k_neighbors_idx = np.argsort(distances, axis=0)[:search_k]#.flatten().tolist()

    k_neighbors = [k_neighbors[i[0]] for i in k_neighbors_idx]
    #k_neighbors[k_neighbors_idx]
    return k_neighbors

In [63]:
# допишите ваш код здесь 
k_neighbors = []
entry_points = np.random.choice(all_documents.shape[0], num_start_points, replace=False)
for i in range(num_start_points):
    #print('new',i)
    entry_point = entry_points[i]
    #print(entry_point)
    new_point = entry_point
    prev_point=-1
    candidates = [new_point]
    while prev_point!=new_point:
        print(candidates)
        point_edges = graph_edges[new_point]
        point_edges = [i for i in point_edges if i not in k_neighbors]
        distances = dist_f(query_point, all_documents[point_edges + [new_point]])
        prev_point = new_point
        new_point = (point_edges + [new_point])[np.argmin(distances)]
        #print(new_point)
        candidates.append(new_point)

        #print(candidates)
    k_neighbors+=candidates[-3:-1]
    print(k_neighbors)

k_neighbors = list(set(k_neighbors))
distances = dist_f(query_point, all_documents[k_neighbors])
k_neighbors_idx = np.argsort(distances, axis=0)[:search_k]#.flatten().tolist()

k_neighbors = [k_neighbors[i[0]] for i in k_neighbors_idx]
#k_neighbors[k_neighbors_idx]
return k_neighbors

[15]
[15, 1]
[15, 1]
[11]
[11, 20]
[15, 1, 11, 20]
[6]
[6, 17]
[15, 1, 11, 20, 6, 17]
[16]
[16, 10]
[15, 1, 11, 20, 6, 17, 16, 10]
[20]
[15, 1, 11, 20, 6, 17, 16, 10, 20]


SyntaxError: 'return' outside function (147040535.py, line 31)

In [58]:
dist_f = distance

In [60]:
search_k = 10

In [62]:
[i for i in point_edges if i not in k_neighbors]

[0, 5, 6, 8, 12, 14, 16, 17, 18, 19]

In [70]:
search_k // num_start_points

2

In [65]:
search_k = 13
num_start_points = 5

In [68]:
from solution_template import *
%load_ext autoreload
%autoreload 2
data = np.concatenate([np.array([[0,0], [1,1], [1,2], [2,1], [3,1], [3,3], [3,-1]]), np.random.rand(10000,2)])

query_point = np.array([1,1])

all_documents = data

graph_edges = create_sw_graph(data)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [69]:
nsw(query_point, all_documents, graph_edges)

[490   1] 
_______________
[ 490    1 3791 1717 8381] 
_______________
[ 490    1 3791 1717 8381 2634] 
_______________
[ 490    1 3791 1717 8381 2634 9609 3673  359] 
_______________
[  490     1  3791  1717  8381  2634  9609  3673   359  9219  5181 10000] 
_______________


[1, 8381, 1717, 3791, 359, 3673, 9609, 2634, 10000, 5181]

In [79]:
def create_sw_graph(
        data: np.ndarray,
        num_candidates_for_choice_long: int = 10,
        num_edges_long: int = 5,
        num_candidates_for_choice_short: int = 10,
        num_edges_short: int = 5,
        use_sampling: bool = False,
        sampling_share: float = 0.05,
        dist_f: Callable = distance
    ) -> Dict[int, List[int]]:
    # допишите ваш код здесь 
    result = defaultdict()
    for i, point in enumerate(data): 
        distances = dist_f(point, data)
        candidates = np.argsort(distances, axis=0)

        candidates_long = candidates[-num_candidates_for_choice_long:]
        edges_long = candidates_long[np.random.choice(num_candidates_for_choice_long, num_edges_long, replace=False)]
        #edges_long = np.unique(edges_long)

        candidates_short = candidates[candidates != i][:num_candidates_for_choice_short+1]
        candidates_short = candidates_short[candidates_short != i][:num_candidates_for_choice_short]
        edges_short = candidates_short[np.random.choice(num_candidates_for_choice_short, num_edges_short, replace=False)]
        #edges_short = np.unique(edges_short)

        candidates = np.unique(np.concatenate([edges_long.flatten(), edges_short.flatten()])).tolist()

        result[i] = candidates
        #result[i].append(candidates)
    return result

In [76]:
defaultdict()

defaultdict(None, {})

In [113]:
def nsw(query_point: np.ndarray, all_documents: np.ndarray, 
        graph_edges: Dict[int, List[int]],
        search_k: int = 10, num_start_points: int = 5,
        dist_f: Callable = distance) -> np.ndarray:
    # допишите ваш код здесь 
    numb_per_point = search_k // num_start_points + 1
    #k_neighbors = []
    #k_neighbors = np.array([], dtype=int)
    k_neighbors = defaultdict()
    entry_points = np.random.choice(all_documents.shape[0], num_start_points, replace=False)
    for i in range(num_start_points):
        #print('new',i)
        entry_point = entry_points[i]
        #print(entry_point)
        new_point = entry_point
        prev_point=-1
        #candidates = np.array([new_point], dtype=int)
        candidates = {}
        while prev_point!=new_point:
            #print(candidates)
            point_edges = graph_edges[new_point]
            #point_edges = [i for i in point_edges if i not in k_neighbors]
            distances = dist_f(query_point, all_documents[point_edges + [new_point]])
            prev_point = new_point
            new_point = (point_edges + [new_point])[np.argmin(distances)]
            new_dist = np.min(distances)
            #print(new_point)
            #candidates.append(new_point)
            #print(candidates)
            #candidates = np.concatenate([candidates, np.array([new_point], dtype=int)])
            
            k_neighbors[new_point] = new_dist
            #print(candidates)
        #k_neighbors+=candidates[-1 - numb_per_point:-1]
        #print(candidates[-1 - numb_per_point:-1])
        #k_neighbors = np.concatenate([k_neighbors, candidates[-1 - numb_per_point:-1]])
        #print(k_neighbors, '\n_______________')

    #k_neighbors = list(set(k_neighbors))
    return list(dict(sorted(k_neighbors.items(), key=lambda x: x[1])[:search_k]).keys())
#     k_neighbors = np.unique(k_neighbors.flatten()).tolist()
#     distances = dist_f(query_point, all_documents[k_neighbors])
#     k_neighbors_idx = np.argsort(distances, axis=0)[:search_k]#.flatten().tolist()

#     k_neighbors = [k_neighbors[i[0]] for i in k_neighbors_idx]
#     #k_neighbors[k_neighbors_idx]
#     return k_neighbors


In [84]:
# %%time
# create_sw_graph(all_documents)

In [116]:
%%time
a = nsw(query_point, all_documents, graph_edges)

CPU times: user 3.66 ms, sys: 0 ns, total: 3.66 ms
Wall time: 2.98 ms


In [98]:
OrderedDict(sorted(a.items())[:10])

OrderedDict([(1, 0.0),
             (608, 0.6578129431134905),
             (717, 0.3590938555118491),
             (992, 0.4338305524335377),
             (1017, 0.262612750703719),
             (1100, 0.2279345740410995),
             (1103, 0.5917839452120786),
             (1147, 0.4739897068318367),
             (1253, 0.2892281267001507),
             (1450, 0.005257349344286137)])

In [112]:
list(dict(sorted(a.items(), key=lambda x: x[1])[:10]).keys())

[1, 1450, 4648, 4290, 2864, 5525, 6041, 1100, 5636, 2220]

In [28]:
%%time
nsw(query_point, all_documents, graph_edges)

[4174, 1475, 1] 
_______________
[4174, 1475, 1, 6226, 2146, 805] 
_______________
[4174, 1475, 1, 6226, 2146, 805, 6491, 8194] 
_______________
[4174, 1475, 1, 6226, 2146, 805, 6491, 8194, 5637, 7380, 9875] 
_______________
[4174, 1475, 1, 6226, 2146, 805, 6491, 8194, 5637, 7380, 9875, 8266, 6210, 2706] 
_______________
CPU times: user 3.46 ms, sys: 107 µs, total: 3.56 ms
Wall time: 2.93 ms


[1, 1475, 8194, 9875, 7380, 5637, 805, 2146, 6226, 2706]

In [42]:
k_neighbors

NameError: name 'k_neighbors' is not defined

In [45]:
all_documents

array([[0.        , 0.        ],
       [1.        , 1.        ],
       [1.        , 2.        ],
       ...,
       [0.57255137, 0.77389264],
       [0.77965083, 0.98591934],
       [0.78851623, 0.29600078]])

In [37]:
np.concatenate([a,a])[1:4]

array([4, 5, 6])