In [1]:
from solution_template import *
%load_ext autoreload
%autoreload 2

In [2]:
entity = Solution(n_estimators=100)

len(key_query_ids) 87
len(key_query_ids) 88
key_query_ids_train shape -  (87,)
key_query_ids_test shape -  (88,)
index_query_ids_train shape -  (10000,)
index_query_ids_test shape -  (10000,)
query_ids_train shape -  (10000,)
query_ids_test shape -  (10000,)
n_sample 6000
n_cols 81


In [3]:
entity.load_model('model.pkl')

In [3]:
entity.fit()

tree n 0
tree n 1
tree n 2
tree n 3
tree n 4
tree n 5
tree n 6
tree n 7
tree n 8
tree n 9
tree n 10
tree n 11
tree n 12
tree n 13
tree n 14
tree n 15
tree n 16
tree n 17
tree n 18
tree n 19
tree n 20
tree n 21
tree n 22
tree n 23
tree n 24
tree n 25
tree n 26
tree n 27
tree n 28
tree n 29
tree n 30
tree n 31
tree n 32
tree n 33
tree n 34
tree n 35
tree n 36
tree n 37
tree n 38
tree n 39
tree n 40
tree n 41
tree n 42
tree n 43
tree n 44
tree n 45
tree n 46
tree n 47
tree n 48
tree n 49
tree n 50
tree n 51
tree n 52
tree n 53
tree n 54
tree n 55
tree n 56
tree n 57
tree n 58
tree n 59
tree n 60
tree n 61
tree n 62
tree n 63
tree n 64
tree n 65
tree n 66
tree n 67
tree n 68
tree n 69
tree n 70
tree n 71
tree n 72
tree n 73
tree n 74
tree n 75
tree n 76
tree n 77
tree n 78
tree n 79
tree n 80
tree n 81
tree n 82
tree n 83
tree n 84
tree n 85
tree n 86
tree n 87
tree n 88
tree n 89
tree n 90
tree n 91
tree n 92
tree n 93
tree n 94
tree n 95
tree n 96
tree n 97
tree n 98
tree n 99
[0.3575859

0.4065735258366334

In [4]:
entity.save_model('model.pkl')

In [11]:
a = entity.load_model(path='model.pkl')

In [13]:
len(entity.trees)

93

In [5]:
entity._calc_data_ndcg(queries_list=entity.query_ids_test, true_labels=entity.ys_test, preds=entity.predict(entity.X_test))

tree n 0
tree n 1
tree n 2
tree n 3
tree n 4
tree n 5
tree n 6
tree n 7
tree n 8
tree n 9
tree n 10
tree n 11
tree n 12
tree n 13
tree n 14
tree n 15
tree n 16
tree n 17
tree n 18
tree n 19
tree n 20
tree n 21
tree n 22
tree n 23
tree n 24
tree n 25
tree n 26
tree n 27
tree n 28
tree n 29
tree n 30
tree n 31
tree n 32
tree n 33
tree n 34
tree n 35
tree n 36
tree n 37
tree n 38
tree n 39
tree n 40
tree n 41
tree n 42
tree n 43
tree n 44
tree n 45
tree n 46
tree n 47
tree n 48
tree n 49
tree n 50
tree n 51
tree n 52
tree n 53
tree n 54
tree n 55
tree n 56
tree n 57
tree n 58
tree n 59
tree n 60
tree n 61
tree n 62
tree n 63
tree n 64
tree n 65
tree n 66
tree n 67
tree n 68
tree n 69
tree n 70
tree n 71
tree n 72
tree n 73
tree n 74
tree n 75
tree n 76
tree n 77
tree n 78
tree n 79
tree n 80
tree n 81
tree n 82
tree n 83
tree n 84
tree n 85
tree n 86
tree n 87
tree n 88
tree n 89
tree n 90
tree n 91


0.42341589660432

In [ ]:
entity.predict(entity.X_train)

In [9]:
entity.trees

[DecisionTreeRegressor(max_depth=5, min_samples_leaf=8),
 DecisionTreeRegressor(max_depth=5, min_samples_leaf=8)]

In [35]:
entity.predict(entity.X_test)

tree n 0
tree n 1
tree n 2
tree n 3
tree n 4
tree n 5
tree n 6


tensor([[-0.0240],
        [-0.1361],
        [-0.0853],
        ...,
        [-0.0835],
        [-0.1802],
        [ 0.7064]])

In [38]:
entity._calc_data_ndcg(queries_list=entity.query_ids_train, true_labels=entity.ys_train, preds=entity.predict(entity.X_train))

tree n 0
tree n 1
tree n 2
tree n 3
tree n 4
tree n 5
tree n 6
[0.6034024973934204]
[0.6034024973934204, 0.18763120066104874]
[0.6034024973934204, 0.18763120066104874, 0.6648933030776826]
[0.6034024973934204, 0.18763120066104874, 0.6648933030776826, 0.5567285146595288]
[0.6034024973934204, 0.18763120066104874, 0.6648933030776826, 0.5567285146595288, 0.5519018779582582]
[0.6034024973934204, 0.18763120066104874, 0.6648933030776826, 0.5567285146595288, 0.5519018779582582, 0.892404383661656]
[0.6034024973934204, 0.18763120066104874, 0.6648933030776826, 0.5567285146595288, 0.5519018779582582, 0.892404383661656, 0.7731227354521711]
[0.6034024973934204, 0.18763120066104874, 0.6648933030776826, 0.5567285146595288, 0.5519018779582582, 0.892404383661656, 0.7731227354521711, 0.0]
[0.6034024973934204, 0.18763120066104874, 0.6648933030776826, 0.5567285146595288, 0.5519018779582582, 0.892404383661656, 0.7731227354521711, 0.0, 0.7539227444117028]
[0.6034024973934204, 0.18763120066104874, 0.6648933030

0.5070125826060637

In [34]:
len([0.4207210228529656, 0.5851105815910258, 0.40154198245948414, 0.6865610096123224, 0.28004404331911975, 0.163463259685217, 0.16976455154021863, 0.3259957729283431, 0.44929075130789053, 0.0, 0.1875427323634819, 0.39481896440459074, 0.21471872627926383, 0.299757604643783, 0.1681522864689108, 0.3411601132299433, 0.1480409554829326, 0.19033909598408683, 0.30394091327354994, 0.4199802373868744, 0.8155378333103152, 0.48293731140876567, 0.1336567862966319, 0.28293002433993253, 0.1507011896156443, 0.520655857157188, 0.28368006653871547, 0.7029328979017053, 0.4130812508605754, 0.4904066305535969, 0.3375494205498825, 0.6530279269760505, 0.3957894701495809, 0.05367885622954803, 0.5028762811468662, 0.2606332067841535, 0.7510518837458089, 0.3909815356509322, 0.5224107387093467, 0.291037243892823, 0.22214445806944938, 0.435231800096633, 0.3428829739444803, 0.4040817569728006, 0.16587075823363845, 0.2479067785140366, 0.5540453237898172, 0.5542462294982037, 0.6031670876953623, 0.048217497477688116, 0.046369706522146746, 0.09082312916052238, 0.1314984114602597, 0.42546599800298174, 0.24924199037643666, 0.511101468428286, 0.47488669934464933, 0.05606364866560146, 0.40951647308499867, 0.6895661650909991, 0.4640852450521883, 0.6614118709914654, 0.18807930214569005, 0.19815748579474593, 0.8050529878921351, 0.19371474872364988, 0.19019924093126508, 0.6749293377968405, 0.7443802385826697, 0.5548338015204686, 0.29453387094064803, 0.4175864567249367, 0.3509423827021353, 0.11043831135927011, 0.12458320007083716, 0.5070069809060479, 0.5031531704150416, 0.6030064543507835, 0.41804441864040404, 0.24399082144165535, 0.26981741632715833, 0.4360511808963442, 0.22863828704545555, 0.7084728633154231, 0.9837663314698345, 0.5235005324049925, 0.21778556506848928, 1.0])

88

In [18]:
for i in np.unique(entity.query_ids_test[:1]):
    idx = np.where((entity.query_ids_test)==i)

In [21]:
ys_true = entity.ys_test[idx]
ys_pred = entity.predict(entity.X_test)[idx]

tree n 0
tree n 1
tree n 2
tree n 3
tree n 4
tree n 5
tree n 6
tree n 7
tree n 8
tree n 9


In [22]:
ys_true

tensor([[2.],
        [1.],
        [3.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [2.],
        [1.],
        [1.],
        [2.],
        [2.],
        [1.],
        [2.],
        [1.],
        [2.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [2.],
        [2.],
        [2.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [3.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [2.],
        [0.],
        [2.],
        [1.],
        [0.],
        [0.],
        [0.],
        [2.],
        [1.],
        [1.],
        [1.],
        [3.],
        [2.],
        [0.],
        [0.],
        [1.],
        [0.],
        [2.],
        [1.],
        [2.],
        [1.],
        [2.],
        [1.],
      

In [25]:
ys_pred.shape

torch.Size([138, 10000])

In [4]:
torch.randperm(10000)[:6000]

tensor([8754, 8138, 3382,  ..., 4380, 9510, 3964])

In [5]:
tree_subsample_idx = torch.randperm(entity.X_train.shape[0])[:entity.n_sample]
tree_cols_idx = torch.randperm(entity.X_train.shape[1])[:entity.n_cols]
tree_X_train = entity.X_train[tree_subsample_idx, tree_cols_idx]

IndexError: shape mismatch: indexing tensors could not be broadcast together with shapes [6000], [122]

In [6]:
tree_subsample_idx

tensor([9719, 3461, 9130,  ..., 3312, 3600, 8626])

In [7]:
tree_cols_idx

tensor([131, 103,  75,  92,  62, 130,  90,  58,  29,   8, 101,  79,  57,  38,
         97, 114, 117,  88, 118,  84, 127,  83,   3, 106,  80,   1,  65,  49,
         47, 105,  43,  72, 119,  17,  99,  82, 110, 116,  95,   9,  94,  33,
         10,  34,  11,  70,  89, 134,  59,  23,  48,  77,  71,  31, 102, 125,
         50, 135,  19,  96,  27, 111,  13,  78,  56,  37, 121,  36,  93,  45,
         76,  42,  66,   4,  52,  91,  73,  85, 108,  87,  54,  74, 133,  81,
         22,  16, 132,  14,  32,  30,  53,  63,   0,  86,  61, 100, 104, 115,
          5, 122, 129, 124,  68,  35,  60,  41,  28,  25,  21,   2, 113, 112,
        107, 128,  24,  39, 120,   6,  67,  64,   7,  26])

In [10]:
entity.X_train[tree_subsample_idx]#[tree_cols_idx]#.shape

torch.Size([122, 136])

In [13]:
torch.index_select(entity.X_train, 1, tree_cols_idx).shape

torch.Size([10000, 122])

In [5]:
entity.trees[0].tree_

In [10]:
for i in entity.key_query_ids_train:
    print(i)

1
16
31
46
61
76
91
106
121
136
151
166
181
196
211
226
241
256
271
286
301
316
331
346
361
376
391
406
421
436
451
466
481
496
511
526
541
556
571
586
601
616
631
646
661
676
691
706
721
736
751
766
781
796
811
826
841
856
871
886
901
916
931
946
961
976
991
1006
1021
1036
1051
1066
1081
1096
1111
1126
1141
1156
1171
1186
1201
1216
1231
1246
1261
1276
1291


In [7]:
torch.zeros(5, 1)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [4]:
entity.X_train

tensor([[ 0.3161,  4.8171, -2.1759,  ..., -0.1118, -0.1959, -0.2662],
        [ 0.3161, -0.2350,  0.6171,  ..., -0.1118, -0.1959, -0.2662],
        [ 0.3161, -0.2350, -0.3139,  ..., -0.1118, -0.1959, -0.2662],
        ...,
        [ 0.4786, -0.4121,  1.3276,  ...,  0.0000, -0.1552, -0.3721],
        [ 0.4786, -0.4121, -0.0675,  ...,  0.0000, -0.1552, -0.3721],
        [ 0.4786,  1.7170, -0.0675,  ...,  0.0000, -0.1552, -0.3721]])

In [5]:
entity.query_ids_train

array([   1,    1,    1, ..., 1291, 1291, 1291])

In [6]:
entity.key_query_ids_train

array([   1,   16,   31,   46,   61,   76,   91,  106,  121,  136,  151,
        166,  181,  196,  211,  226,  241,  256,  271,  286,  301,  316,
        331,  346,  361,  376,  391,  406,  421,  436,  451,  466,  481,
        496,  511,  526,  541,  556,  571,  586,  601,  616,  631,  646,
        661,  676,  691,  706,  721,  736,  751,  766,  781,  796,  811,
        826,  841,  856,  871,  886,  901,  916,  931,  946,  961,  976,
        991, 1006, 1021, 1036, 1051, 1066, 1081, 1096, 1111, 1126, 1141,
       1156, 1171, 1186, 1201, 1216, 1231, 1246, 1261, 1276, 1291])

In [ ]:
entity.query_ids_train

In [7]:
for i in range(len(entity.key_query_ids_train[:1])):
    batch_X = entity.X_train[np.where(entity.index_query_ids_test==i)]
    batch_y = entity.ys_train[np.where(entity.index_query_ids_test==i)]
    print(np.where(entity.index_query_ids_test==i))
    

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137]),)


In [ ]:
batch_X = self.X_test[np.where(self.index_query_ids_test==i)]
batch_y = self.ys_test[np.where(self.index_query_ids_test==i)]

In [8]:
a = np.where(entity.index_query_ids_test==i)

In [13]:
a[0].add(a[0])

AttributeError: 'numpy.ndarray' object has no attribute 'add'

In [16]:
np.concatenate([a[0],a[0]])

ValueError: zero-dimensional arrays cannot be concatenated

In [19]:
np.array(None, 1,0)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [22]:
a = entity._compute_lambdas(y_true=entity.ys_train[np.where(entity.index_query_ids_test==i)], 
                                                y_pred=entity.ys_train[np.where(entity.index_query_ids_test==i)])

In [25]:
torch.cat([a,a]).shape

torch.Size([276, 1])

In [27]:
a.shape

torch.Size([138, 1])

In [6]:
torch.tensor([[-0.2818],
        [-2.8954],
        [ 0.0685]]).shape

torch.Size([3, 1])

In [24]:
curr_idx = np.where(entity.index_query_ids_train==7)

In [25]:
y_true=entity.ys_train[curr_idx]
#y_pred=train_preds[curr_idx]

In [26]:
y_pred = torch.zeros(y_true.shape[0])

In [27]:
y_true

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [8]:
y_true_sorted_ideal, _ = torch.sort(y_true, 0, descending=True)
ideal_dcg = 0
for i, val in enumerate(y_true_sorted_ideal):
    val = float(2 ** val - 1) / math.log2(i+2)
    ideal_dcg += val
N = 1 / ideal_dcg 

In [9]:
y_true_sorted_ideal, _ = torch.sort(y_true, 0, descending=True)

In [18]:
curr_idx

(array([ 878,  879,  880,  881,  882,  883,  884,  885,  886,  887,  888,
         889,  890,  891,  892,  893,  894,  895,  896,  897,  898,  899,
         900,  901,  902,  903,  904,  905,  906,  907,  908,  909,  910,
         911,  912,  913,  914,  915,  916,  917,  918,  919,  920,  921,
         922,  923,  924,  925,  926,  927,  928,  929,  930,  931,  932,
         933,  934,  935,  936,  937,  938,  939,  940,  941,  942,  943,
         944,  945,  946,  947,  948,  949,  950,  951,  952,  953,  954,
         955,  956,  957,  958,  959,  960,  961,  962,  963,  964,  965,
         966,  967,  968,  969,  970,  971,  972,  973,  974,  975,  976,
         977,  978,  979,  980,  981,  982,  983,  984,  985,  986,  987,
         988,  989,  990,  991,  992,  993,  994,  995,  996,  997,  998,
         999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009,
        1010, 1011, 1012, 1013, 1014]),)

In [10]:
entity.ys_train[curr_idx]

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [9]:
y_true

tensor([[1.],
        [2.],
        [2.],
        [1.],
        [0.],
        [3.],
        [1.],
        [2.],
        [0.],
        [2.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [2.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [2.],
        [0.],
        [1.],
        [2.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [1.],
        [2.],
        [2.],
        [2.],
        [0.],
        [1.],
        [1.],
        [2.],
        [0.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [1.],
        [2.],
        [2.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [2.],
        [0.],
        [2.],
        [2.],
        [3.],
        [1.],
        [1.],
        [2.],
        [2.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [2.],
        [1.],
        [1.],
        [2.],
      

In [22]:
curr_idx = np.where(entity.index_query_ids_train==7)
curr_lamdas = entity._compute_lambdas(y_true=entity.ys_train[curr_idx], 
                                    y_pred=None)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
0.0


ZeroDivisionError: float division by zero

In [23]:
curr_idx

(array([582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594,
        595, 596, 597, 598, 599, 600, 601, 602, 603, 604]),)

In [7]:
y_true=entity.ys_train[curr_idx]

In [17]:
y_true_sorted_ideal, _ = torch.sort(y_true, 0, descending=True)
print(y_true)
print(y_true_sorted_ideal)
ideal_dcg = 0
for i, val in enumerate(y_true_sorted_ideal):
    val = float(2 ** val - 1) / math.log2(i+2)
    ideal_dcg += val
print(ideal_dcg)
N = 1 / ideal_dcg

tensor([[1.],
        [2.],
        [2.],
        [1.],
        [0.],
        [3.],
        [1.],
        [2.],
        [0.],
        [2.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [2.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [2.],
        [0.],
        [1.],
        [2.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [1.],
        [2.],
        [2.],
        [2.],
        [0.],
        [1.],
        [1.],
        [2.],
        [0.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [1.],
        [2.],
        [2.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [2.],
        [0.],
        [2.],
        [2.],
        [3.],
        [1.],
        [1.],
        [2.],
        [2.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [2.],
        [1.],
        [1.],
        [2.],
      

In [8]:
y_true

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [16]:
torch.sort(y_true, 0, descending=True)

torch.return_types.sort(
values=tensor([[4.],
        [4.],
        [3.],
        [3.],
        [3.],
        [3.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
  