In [1]:
from solution_template import *

/home/karpov/LTR/loss_f/solution_template.py:126: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(batch_y.shape == batch_pred.shape,
/home/karpov/LTR/loss_f/solution_template.py:147: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(batch_y.shape == batch_pred.shape,


In [2]:
entity = Solution()

len(key_query_ids) 87
len(key_query_ids) 88
key_query_ids_train shape -  (87,)
key_query_ids_test shape -  (88,)
index_query_ids_train shape -  (10000,)
index_query_ids_test shape -  (10000,)
query_ids_train shape -  (10000,)
query_ids_test shape -  (10000,)
shapes -  torch.Size([10000, 136]) torch.Size([10000]) torch.Size([10000, 136]) torch.Size([10000])
num_input_features -  136


In [3]:
entity.fit()

/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


epoch number -  0
nDCG: 0.4258
epoch number -  1
nDCG: 0.4328
epoch number -  2
nDCG: 0.4368
epoch number -  3
nDCG: 0.4411
epoch number -  4
nDCG: 0.4428


[0.4258056561587274,
 0.43284113601900687,
 0.43677268654662504,
 0.4410818320541503,
 0.4427903300627822]

In [ ]:
entity.key_query_ids_train

In [ ]:
ndcgs = []
for i in range(len(entity.key_query_ids_test)):
    batch_X = entity.X_test[np.where(entity.index_query_ids_test==i)]

    batch_y = entity.ys_test[np.where(entity.index_query_ids_test==i)]
    #batch_pred = self.model(batch_X)
    batch_pred = torch.reshape(entity.model(batch_X), (-1,))
    
    ys_true_sorted_ideal, _ = torch.sort(batch_y, 0, descending=True)
    ideal_dcg = 0
    for i, val in enumerate(ys_true_sorted_ideal[:10]):
        val = float(2 ** val - 1) / math.log2(i+2)
        ideal_dcg += val
        #print(ideal_dcg)
        
    _, indices = torch.sort(batch_pred, 0, descending=True)
    ys_true_sorted = batch_y[indices]

    res1 = 0
    for i, val in enumerate(ys_true_sorted[:10]):
        val = float(2 ** val - 1) / math.log2(i+2)
        #print(res1)
        res1 += val


    ndcgs.append(res1/ideal_dcg)

In [31]:
ndcgs

[0.2784808704076345,
 0.05741859610747236,
 0.039778124727598806,
 0.02284347945217883,
 0.15582954353930173,
 0.29461563293075727,
 0.2588858297196561,
 0.2838300191112332,
 0.09641996365784913,
 0.0,
 0.10265504771876915,
 0.12774258911509878,
 0.061178746022272364,
 0.022274431926388602,
 0.31516255047698366,
 0.035539222204391756,
 0.5931729515195112,
 0.0,
 0.36167535192008093,
 0.1706274132625464,
 0.49002192910592896,
 0.06837222244264786,
 0.3377640579349909,
 0.2024328629296542,
 0.3904561715346295,
 0.0551766108408796,
 0.17704936061739537,
 0.2811202685788958,
 0.034297406047765065,
 0.5777760312307709,
 0.1596243998692697,
 0.43064716772928785,
 0.3561084549156445,
 0.37156095747975126,
 0.19474673412652152,
 0.04398192885285911,
 0.09582471095738956,
 0.06968503698698301,
 0.5791179725958181,
 0.16279766337189053,
 0.17364419587639968,
 0.33441080365972076,
 0.32384489865183047,
 0.2657470347490216,
 0.05085424539272843,
 0.21497843467059594,
 0.38520851554049473,
 0.15100

In [28]:
np.mean(ndcgs)

0.20666408172480139

In [13]:
batch_X = entity.X_test[np.where(entity.index_query_ids_test==0)]

batch_y = entity.ys_test[np.where(entity.index_query_ids_test==0)]
#batch_pred = self.model(batch_X)
batch_pred = torch.reshape(entity.model(batch_X), (-1,))

In [14]:
ys_true_sorted_ideal, _ = torch.sort(batch_y, 0, descending=True)

In [15]:
batch_X[:,1].shape

torch.Size([138])

In [19]:
batch_X[:,8].mean()

tensor(0.0467)

In [22]:
batch_X[:,100].std()

tensor(0.9634)

In [35]:
ideal_dcg = 0
for i, val in enumerate(ys_true_sorted_ideal[:10]):
    val = float(2 ** val - 1) / math.log2(i+2)
    ideal_dcg += val
    print(ideal_dcg)

3.0
4.892789260714372
5.392789260714372
5.392789260714372
5.392789260714372
5.392789260714372
5.392789260714372
5.392789260714372
5.392789260714372
5.392789260714372


In [36]:
float(2 ** 3 - 1) / math.log2(2)

7.0

In [38]:
_, indices = torch.sort(batch_pred, 0, descending=True)

ys_true_sorted = batch_y[indices]
print(ys_true_sorted)

res1 = 0
for i, val in enumerate(ys_true_sorted[:10]):
    val = float(2 ** val - 1) / math.log2(i+2)
    print(res1)
    res1 += val
    

res1/ideal_dcg

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 2., 0., 0., 0., 0., 0.])
0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


0.0

In [ ]:
_, indices = torch.sort(ys_pred, 0, descending=True)
        ys_true_sorted = ys_true[indices]
        res = 0
        try:
            for i, val in enumerate(ys_true_sorted[:ndcg_top_k]):
                val = float(2 ** val - 1) / math.log2(i+2)
                res += val

In [14]:
indices

tensor([ 89,  46, 114, 101,  98, 123, 109,  45, 129,   0,   7,  26,   3,  56,
         99,   1,  20,  58,  21,  17, 112,  93, 128,  90, 134,  77, 106, 133,
        126,  88,  87, 120,  84, 136,  97, 116,   8,  30,  61, 122,  31,  86,
        110,  57,  52,  96,  33, 135,  83,  69,   5, 102,  25, 117, 127,   6,
        118, 121, 119,  41,  23,   4, 125,  95, 105,  65,  28,  12,  91,  48,
        115, 131,  14, 104, 100,  76, 124, 130,  68,  49,  92,  16, 107,  51,
         82,  64,  39,  63,   9,  80,  38,  37,  15,  55,  27,  24,  22,  53,
         43,  32,  67,  29,  18,  50,  62,  19,  71,  75,  70,  35,  10,  73,
         47,  36,  60,  85,  11,   2,  34,  66,  54,  72,  74,  79,  59,  81,
         78,  42,  44, 113,  40, 108,  13, 111,  94, 137, 132, 103])

In [ ]:
ys_true_sorted_ideal, _ = torch.sort(ys_true, 0, descending=True)
        ideal_dcg = 0
        try:
            for i, val in enumerate(ys_true_sorted_ideal[:ndcg_top_k]):
                val = float(2 ** val - 1) / math.log2(i+2)
                ideal_dcg += val
            res = self._dcg_k(ys_true, ys_pred, ndcg_top_k)

In [7]:
rand_idx = torch.randperm(len(entity.key_query_ids_train))

In [8]:
torch.reshape(entity.model(entity.X_train[np.where(entity.query_ids_train==entity.key_query_ids_train[0])]), (-1,))

tensor([0.3526, 0.3519, 0.3532, 0.3537, 0.3521, 0.3527, 0.3525, 0.3528, 0.3519,
        0.3519, 0.3514, 0.3577, 0.3521, 0.3527, 0.3525, 0.3520, 0.3527, 0.3524,
        0.3529, 0.3527, 0.3521, 0.3519, 0.3524, 0.3521, 0.3524, 0.3519, 0.3524,
        0.3502, 0.3519, 0.3527, 0.3524, 0.3519, 0.3531, 0.3510, 0.3530, 0.3521,
        0.3523, 0.3522, 0.3533, 0.3529, 0.3532, 0.3519, 0.3522, 0.3521, 0.3525,
        0.3520, 0.3528, 0.3523, 0.3531, 0.3519, 0.3521, 0.3521, 0.3527, 0.3519,
        0.3530, 0.3525, 0.3527, 0.3564, 0.3520, 0.3525, 0.3521, 0.3523, 0.3519,
        0.3525, 0.3524, 0.3522, 0.3521, 0.3519, 0.3519, 0.3529, 0.3519, 0.3519,
        0.3521, 0.3519, 0.3525, 0.3519, 0.3527, 0.3519, 0.3519, 0.3525, 0.3526,
        0.3525, 0.3526, 0.3521, 0.3529, 0.3524], grad_fn=<ViewBackward>)

In [19]:
np.where(entity.query_ids_train==entity.key_query_ids_train[0])


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85]),)

In [17]:
entity.X_train[np.where(entity.query_ids_train==entity.key_query_ids_train[0])].shape

torch.Size([86, 136])

In [16]:
entity.ys_train[np.where(entity.query_ids_train==entity.key_query_ids_train[0])].shape

torch.Size([86])

In [4]:
entity.index_query_ids_test

array([ 0,  0,  0, ..., 86, 87, 87])

In [9]:
entity.index_query_ids_train

array([ 0,  0,  0, ..., 86, 86, 86])

In [6]:
entity.index_query_ids_test

array([ 0,  0,  0, ..., 86, 87, 87])

In [10]:
entity.X_train[np.where(entity.index_query_ids_train==67)]

tensor([[ 0.3903, -0.5018,  0.6980,  ..., -0.1440, -0.1159, -0.4529],
        [ 0.3903, -0.5018,  0.6980,  ..., -0.1440, -0.1159, -0.4529],
        [ 0.3903, -0.5018,  0.6980,  ..., -0.1440, -0.1159, -0.4529],
        ...,
        [ 0.3903, -0.5018,  0.6980,  ..., -0.1440, -0.0888,  1.1247],
        [-2.5623,  1.9928, -1.4327,  ..., -0.1440, -0.1159, -0.4529],
        [ 0.3903, -0.5018,  0.6980,  ..., -0.1440, -0.1159, -0.4529]])

In [5]:
import pandas as pd 
pd.Series(y_train).value_counts()

0.0    5481
1.0    3000
2.0    1326
3.0     142
4.0      51
dtype: int64

In [6]:
pd.Series(query_ids_train).value_counts().sort_index(ascending=True)

1        86
16      106
31       92
46      120
61       59
       ... 
1231    156
1246    133
1261    107
1276     52
1291    124
Length: 87, dtype: int64

In [51]:
key_query_ids, index_query_ids = np.unique(query_ids_train, return_inverse=True)

batch = X_train[np.where(index_query_ids == 0)]
scaled_X = StandardScaler().fit_transform(batch)

for i in range(len(key_query_ids) - 1):
    batch = X_train[np.where(index_query_ids == i+1)]
    scaled_batch = StandardScaler().fit_transform(batch)
    scaled_X = np.concatenate((scaled_X, scaled_batch), axis=0)

In [52]:
scaled_X.shape

(10000, 136)

In [47]:
np.concatenate((scaled_X, scaled_batch), axis=0).shape

(172, 136)

In [24]:
pd.DataFrame(X_train[:,0]).transform(lambda x: StandardScaler().fit_transform(x))

ValueError: Function did not transform

In [21]:
pd.DataFrame(X_train[:,0]).groupby(query_ids_train)[0].transform(lambda x: scaler().fit_transform(x))

TypeError: 'StandardScaler' object is not callable

In [16]:
pd.DataFrame(X_train[:, 0]).groupby(query_ids_train).transform(lambda x: scaler().fit_transform(x.values[:,np.newaxis]).ravel())

TypeError: Transform function invalid for data types

In [ ]:
np.split(a[:,1], np.unique(a[:, 0], return_index=True)[1][1:])

In [8]:
X_train

array([[3., 3., 0., ..., 0., 0., 0.],
       [3., 0., 3., ..., 0., 0., 0.],
       [3., 0., 2., ..., 0., 0., 0.],
       ...,
       [2., 0., 2., ..., 0., 0., 0.],
       [2., 0., 1., ..., 0., 0., 0.],
       [2., 1., 1., ..., 0., 0., 0.]])

In [17]:
np.unique(np.stack(y_train), return_inverse=True, axis=0)

(array([0., 1., 2., 3., 4.]), array([2, 2, 0, ..., 2, 2, 1]))

In [18]:
np.stack(y_train)

array([2., 2., 0., ..., 2., 2., 1.])

In [29]:
key_query_ids, index_query_ids = np.unique(query_ids_train, return_inverse=True)

In [27]:
#np.unique(query_ids_train, return_inverse=True)[0].shape, np.unique(query_ids_train, return_inverse=True)[1].shape

((87,), (10000,))

In [28]:
#X_train.shape

(10000, 136)

In [71]:
index_query_ids

array([ 0,  0,  0, ..., 86, 86, 86])

ERROR! Session/line number was not unique in database. History logging moved to new session 39


In [ ]:
a = np.empty(len(key_query_ids), dtype=np.int64)
a[0] = [0,1]

In [63]:
values = np.zeros((len(key_query_ids), X_train.shape[0]), dtype=np.int64) 

In [59]:
np.add.at(values, index_query_ids, X_train)  

ValueError: array is not broadcastable to correct shape

In [70]:
a

array([     94762245727120,                   0,                 639,
                        -1,                 228,                   0,
       8247626271117419042, 8026294580820582510, 2334102057476976749,
       7236828443251860852, 2338621003134951712, 7813865678659675759,
        733650707460748389, 2314885530818453514, 8387230146345652256,
       2314885530454815333, 3255307777494491168, 2308707431035514157,
       8367723430004400160, 8391085964746061925, 2314885437525485938,
       2314885530818453536, 7956016061199958304, 8675467939705462887,
       2334379873309827188, 7310579611546251107, 5269246947816841316,
       7305437204000743540, 6998715202991122208, 2340029507616186483,
       2314885530453831265, 2314885530818453536, 2334097595258072681,
       8083791381042831457, 2336927755367183215, 7310011937162092912,
       2318912240199755552, 8316293034885925152, 8367736921893462816,
       2314885530817029480, 7142744331359625248, 8243122671931387247,
       2334672639822

ERROR! Session/line number was not unique in database. History logging moved to new session 38


In [62]:
key_query_ids

array([   1,   16,   31,   46,   61,   76,   91,  106,  121,  136,  151,
        166,  181,  196,  211,  226,  241,  256,  271,  286,  301,  316,
        331,  346,  361,  376,  391,  406,  421,  436,  451,  466,  481,
        496,  511,  526,  541,  556,  571,  586,  601,  616,  631,  646,
        661,  676,  691,  706,  721,  736,  751,  766,  781,  796,  811,
        826,  841,  856,  871,  886,  901,  916,  931,  946,  961,  976,
        991, 1006, 1021, 1036, 1051, 1066, 1081, 1096, 1111, 1126, 1141,
       1156, 1171, 1186, 1201, 1216, 1231, 1246, 1261, 1276, 1291])

In [50]:
X_train[1,1]

0.0

In [37]:
index_query_ids

array([ 0,  0,  0, ..., 86, 86, 86])

In [57]:
X_train[:,1]

array([3., 0., 0., ..., 0., 0., 1.])

In [42]:
X_train[1, :]

array([ 3.0000000e+00,  0.0000000e+00,  3.0000000e+00,  0.0000000e+00,
        3.0000000e+00,  1.0000000e+00,  0.0000000e+00,  1.0000000e+00,
        0.0000000e+00,  1.0000000e+00,  4.0600000e+02,  0.0000000e+00,
        5.0000000e+00,  5.0000000e+00,  4.1600000e+02,  6.9312750e+00,
        2.2076928e+01,  1.9673353e+01,  2.2255383e+01,  6.9265510e+00,
        2.8000000e+01,  0.0000000e+00,  3.0000000e+00,  0.0000000e+00,
        3.1000000e+01,  8.0000000e+00,  0.0000000e+00,  1.0000000e+00,
        0.0000000e+00,  9.0000000e+00,  1.0000000e+01,  0.0000000e+00,
        1.0000000e+00,  0.0000000e+00,  1.1000000e+01,  9.3333330e+00,
        0.0000000e+00,  1.0000000e+00,  0.0000000e+00,  1.0333333e+01,
        8.8888900e-01,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        8.8888900e-01,  6.8966000e-02,  0.0000000e+00,  6.0000000e-01,
        0.0000000e+00,  7.4519000e-02,  1.9704000e-02,  0.0000000e+00,
        2.0000000e-01,  0.0000000e+00,  2.1635000e-02,  2.4631000e-02,
      

In [ ]:
values = np.zeros(len(keys), dtype=np.int64)          # Sum-based accumulator
np.add.at(values, index, df[:,1])  